channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - python=3.5.1
  - samtools=1.3.1
  - snakemake=3.11.0
  - pyyaml=3.11
  - cutadapt=1.12
  - sra-tools=2.9.1
  - minimap2=2.11
  - bamutil=1.0.14
